### ISSUE TITLE
OSError: [Errno 75] Value too large for defined data type

### ISSUE THREAD

**Issue by emilyanncr** [ticarpi/jwt_tool#113]
Running updated version of Kali Linux on a Virtualbox where Windows is the Host

### Anticipated output
*This was indeed the output I received when entering the JWT into the site jwt.io
{
  "iat": 133628760717238400,
  "nonce": "fa47d072-1c37-4ca4-a064-1a81d1270192",
  "clientid": "cef9cdba-e8c2-4abc-b16d-XXXX",
  "recipid": "43d56975-94ed-4caa-94f6-e3e4f74095c3",
  "nbf": 1718402471,
  "exp": 1720994471,
  "iss": "https://internalngicqa.xxx.com/esign/",
  "aud": "https://internalngicqa.xxx.com/esign/"
}

### Actual output:

python3 jwt_tool.py eyJhbGciOiJSUzI1NiIsImtpZCI6IjA2NjczQTlBRUQyMjNEMTcxQzNDMkZEODQxODhGMUZEQjQwOEMzNjIiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjEzMzYyODc2MDcxNzIzODM5Miwibm9uY2UiOiJmYTQ3ZDA3Mi0xYzM3LTRjYTQtYTA2NC0xYTgxZDEyNzAxOTIiLCJjbGllbnRpZCI6ImNlZjljZGJhLWU4YzItNGFiYy1iMTZkLTI0NjMxZGIwNzE1OCIsInJlY2lwaWQiOiI0M2Q1Njk3NS05NGVkLTRjYWEtOTRmNi1lM2U0Zjc0MDk1YzMiLCJuYmYiOjE3MTg0MDI0NzEsImV4cCI6MTcyMDk5NDQ3MSwiaXNzIjoiaHR0cHM6Ly9pbnRlcm5hbG5naWNxYS5uYXRpb25hbGdlbmVyYWwuY29tL2VzaWduLyIsImF1ZCI6Imh0dHBzOi8vaW50ZXJuYWxuZ2ljcWEubmF0aW9uYWxnZW5lcmFsLmNvbS9lc2lnbi8ifQ.r2754YB9qXzIpxilw333Lja0-4zZHW-OHrgwZwtNjFqCQfb72rD1mzKT-09U_HaQaIu-uc0KXnOpFmebn1U1PWhLX_knn97yx3OAToS1dvnpjbYwfXsczlblS3tP1AvXgVXX51aTSFfSNiA9F6USu0cOT-y_QKXuhYLAYscaL1nk0pON8SRxvyz6HsoCdfgGpO8xjO95i8ouU5C6tiCzEzYNwPkzmVicqmBK88NLJYYO1P2KB1NkWGXLHbWwQeD8f62IcGvEXxQUf-_tzyhpqPyKniBkYgh_gHe7exmT6R79u3321BAeAKHcp58zla4i5EmrtJE8WJCDzuLoEYyw7Q

        \   \        \         \          \                    \ 
   \__   |   |  \     |\__    __| \__    __|                    |
         |   |   \    |      |          |       \         \     |
         |        \   |      |          |    __  \     __  \    |
  \      |      _     |      |          |   |     |   |     |   |
   |     |     / \    |      |          |   |     |   |     |   |
\        |    /   \   |      |          |\        |\        |   |
 \______/ \__/     \__|   \__|      \__| \______/  \______/ \__|
 Version 2.2.7                \______|             @ticarpi      

Original JWT: 
                                                                       
=====================
Decoded Token Values:                                                  
=====================                                                  

Token header values:                                                   
[+] alg = "RS256"
[+] kid = "06673A9AED223D171C3C2FD84188F1FDB408C362"
[+] typ = "JWT"

Token payload values:                                                  
Traceback (most recent call last):
  File "/home/emily/Downloads/jwt_tool/jwt_tool.py", line 2103, in <module>
    rejigToken(headDict, paylDict, sig)
  File "/home/emily/Downloads/jwt_tool/jwt_tool.py", line 1299, in rejigToken
    comparestamps, expiredtoken = dissectPayl(paylDict)
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/emily/Downloads/jwt_tool/jwt_tool.py", line 1193, in dissectPayl
    timestamp = datetime.fromtimestamp(int(paylDict[claim]))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 75] Value too large for defined data type
                                                                       

Can you please advise?  Many thanks!!

**Comment by sinSeptember** [comment]
Hey,
You're encountering the `OSError: [Errno 75] Value too large for defined data type` error related to timestamps.
Could you please provide more details about the JWT token that triggered this error?
Specifically, the values of the iat  and exp  timestamps in the token payload would be helpful to diagnose the problem further.
