### ISSUE TITLE
TypeError: the JSON object must be str, bytes or bytearray, not OrderedDict

### ISSUE THREAD

**Issue by noraj** [ticarpi/jwt_tool#115]
I'm using last release 2.2.7.

It seems to be a similar error as in #21 that was fixed in v1.3.5. However, it seems exactly the same issue as in #106

So there is maybe another `json.loads` that should be changed in `json.dumps`.

While decoding a token:

```
Token payload values:
…
[+] prop_a = JSON object:
    [+] aaa = "['stuff_a', 'stuff_b', 'stuff_c', 'stuff_d']"
[+] prop_b = JSON object:
Traceback (most recent call last):
  File "/usr/share/jwt-tool/jwt_tool.py", line 2103, in <module>
    rejigToken(headDict, paylDict, sig)
  File "/usr/share/jwt-tool/jwt_tool.py", line 1299, in rejigToken
    comparestamps, expiredtoken = dissectPayl(paylDict)
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/jwt-tool/jwt_tool.py", line 1203, in dissectPayl
    if type(castInput(paylDict[claim][subclaim])) == str:
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/jwt-tool/jwt_tool.py", line 595, in castInput
    jsonInput = json.loads(newInput)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not OrderedDict
```

The data:

```json
  …
  "prop_a": {
    "aaa": [
      "stuff_a",
      "stuff_b",
      "stuff_c",
      "stuff_d"
    ]
  },
  "prop_b": {
    "bbb": {
      "ccc": [
        "stuff_e",
        "stuff_f",
        "stuff_g"
      ]
    }
  },
  …
```

**Comment by noraj** [comment]
It seems #114 and #111 are trying to fix OrderedDict casting issues.

**Comment by BreakfastSerial** [comment]
I'm facing the same issue, #111 fixed it in my case.

**Comment by cosad3s** [comment]
Same here with release 2.2.7.

For example for Firebase JWT, there are claims like: 

```json
{
  "email": "user@example.com",
  "email_verified": true,
  "firebase": {
    "identities": {
      "email": ["user@example.com"]
    },
    "sign_in_provider": "password"
  }
}
```

`jwt_tool` crashes:

```bash
...
[+] email_verified = False
[+] firebase = JSON object:
Traceback (most recent call last):
  File "/opt/jwt_tool/./jwt_tool.py", line 2103, in <module>
    rejigToken(headDict, paylDict, sig)
  File "/opt/jwt_tool/./jwt_tool.py", line 1299, in rejigToken
    comparestamps, expiredtoken = dissectPayl(paylDict)
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jwt_tool/./jwt_tool.py", line 1203, in dissectPayl
    if type(castInput(paylDict[claim][subclaim])) == str:
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jwt_tool/./jwt_tool.py", line 595, in castInput
    jsonInput = json.loads(newInput)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not OrderedDict

```
