### ISSUE TITLE
TIMESTAMP Error

### ISSUE THREAD

**Issue by m7x** [ticarpi/jwt_tool#20]
Hello there,

I get the following error message. It looks like it is failing on the `TIMESTAMP`:

```
> python3 jwt_tool.py [JWT_TOKEN]

=====================
Decoded Token Values:
=====================

Token header values:
[+] typ = "JWT"
[+] alg = "HS512"

Token payload values:
[+] UserId = "215"
[+] App = "C467**********************"
[+] iss = "************* JWT"
[+] VenueId = 265
[+] UserName = "*************"
[+] VenueName = "*************"
[+] VenueType = 1
[+] SysCategory = 0
[+] aud = "C46***************************************"
[+] exp = 1594211740    ==> TIMESTAMP = 2020-07-08 13:35:40 (UTC)
Traceback (most recent call last):
  File "jwt_tool.py", line 1483, in <module>
    rejigToken(headDict, paylDict, sig)
  File "jwt_tool.py", line 1280, in rejigToken
    comparestamps, expiredtoken = dissectPayl(paylDict)
  File "jwt_tool.py", line 1171, in dissectPayl
    timestamp = datetime.datetime.fromtimestamp(int(paylDict[claim]))
ValueError: invalid literal for int() with base 10: '07/07/2020 12:35:40'
```
Thanks

**Comment by m7x** [comment]
The value of the `iat` is `07/08/2020 09:35:59` . `jwt_tool` is expecting a timestamp and that's why is failing.

**Comment by m7x** [comment]
It looks like the token is not [RFC compliant](https://tools.ietf.org/html/rfc7519):

```
4.1.6.  "iat" (Issued At) Claim

   The "iat" (issued at) claim identifies the time at which the JWT was
   issued.  This claim can be used to determine the age of the JWT.  Its
   value MUST be a number containing a NumericDate value.  Use of this
   claim is OPTIONAL.
```

and then:

```
   NumericDate
      A JSON numeric value representing the number of seconds from
      1970-01-01T00:00:00Z UTC until the specified UTC date/time,
      ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1,
      2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in
      which each day is accounted for by exactly 86400 seconds, other
      than that non-integer values can be represented.  See RFC 3339
      [RFC3339] for details regarding date/times in general and UTC in
      particular.
```

**Comment by ticarpi** [comment]
Yes, looks like the token you're testing is having fun with the RFCs.
Fairly uncommon issue, but I might something to handle errors like this gracefully in v2.0
