### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by emilyanncr** [ticarpi/jwt_tool#46]
Traceback (most recent call last):
  File "/home/emily/Tools/jwt_tool/jwt_tool.py", line 2024, in <module>
    rejigToken(headDict, paylDict, sig)
  File "/home/emily/Tools/jwt_tool/jwt_tool.py", line 1327, in rejigToken
    jwtOut(newContents+"."+sig, "Sending token")
  File "/home/emily/Tools/jwt_tool/jwt_tool.py", line 231, in jwtOut
    resData = sendToken(token, cookiedict, logID, headertoken[0], posttoken[0])
  File "/home/emily/Tools/jwt_tool/jwt_tool.py", line 150, in sendToken
    response = requests.get(url, headers=headers, cookies=cookiedict, proxies=False, verify=False)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 317, in prepare
    self.prepare_headers(headers)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 451, in prepare_headers
    check_header_validity(header)
  File "/usr/lib/python3/dist-packages/requests/utils.py", line 957, in check_header_validity
    raise InvalidHeader("Invalid return character or leading space in header: %s" % name)
requests.exceptions.InvalidHeader: Invalid return character or leading space in header: Authorization

I made sure to triple check that the character/leading space in the header Authorization is correct as well as the rest of the syntax for my arguments.  Any ideas?  Thanks!!
I am using the most recent version of Kali Linux that's running on virtualbox installed on my Windows machine.

**Comment by ticarpi** [comment]
What is the full command you are using? Are you enclosing the Authorization heart text in quotes?

**Comment by emilyanncr** [comment]
@ticarpi hey thanks for responding so quickly!! I was able to get it working.
