### ISSUE TITLE
OrderedDict mutated during iteration

### ISSUE THREAD

**Issue by FallenHero66** [ticarpi/jwt_tool#56]
Hi,
for me, launching the tool produces the following error when checking for external interaction :

Traceback (most recent call last):
  File "/home/csaudit/jwt_tool/jwt_tool.py", line 2098, in <module>
    runScanning()
  File "/home/csaudit/jwt_tool/jwt_tool.py", line 1703, in runScanning
    scanModePlaybook()
  File "/home/csaudit/jwt_tool/jwt_tool.py", line 1489, in scanModePlaybook
    for payloadClaim in backupDict:
RuntimeError: OrderedDict mutated during iteration

It seems to be caused by the del statement in the function _injectExternalInteractionPayload_ (line 1639), as replacing it with a print statement fixes the issue. Am I doing anything wrong or is this a bug?

Best,
FH

**Comment by j0eblow** [comment]
I just ran into the same error. Your suggested fix seems to have worked. Thanks!
